version: 2
jobs:
  deploy:
    docker:
      - image: clue/httpie
    environment:

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            echo 'Old, live import map:'
            http $CF_PUBLIC_URL/fitch.importmap

            echo 'New import map that will be PATCHed to the live map:'
            cat fitch.importmap

            echo "Updating import map"
            http PATCH $DEPLOYER_HOST/import-map.json\?env=$DEPLOYER_ENV -a $DEPLOYER_USERNAME:$DEPLOYER_PASSWORD --check-status < fitch.importmap

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          context: deploy-context
          filters:
            branches:
              only: master
